### ISSUE TITLE
グラフに新しい学習履歴が表示されない

### ISSUE THREAD

**Issue by suntorybikkle** [suntorybikkle/test#14]
![image](https://user-images.githubusercontent.com/60565605/81492103-45cae880-92d0-11ea-8f30-87ef7c37a3b8.png)

上だと5/14の学習履歴が表示されるが、グラフにはない

![image](https://user-images.githubusercontent.com/60565605/81492174-bd007c80-92d0-11ea-9068-63143df4f74b.png)

**Comment by ktguy123** [comment]
対応しました。
