### ISSUE TITLE
リポジトリ名を変えたい

### ISSUE THREAD

**Issue by suntorybikkle** [suntorybikkle/test#19]
testというディレクトリ名は予約語で使われていることもあり、変更したい

アプリケーションの名前募集

ついでに`learning_app`のクライアント側ディレクトリも`web`とかに変更したい

**Comment by ktguy123** [comment]
1.「Otter」
2. 「Recody」
3. 「LIT」

**Comment by suntorybikkle** [comment]
@ktguy123  
申し訳ない、提案があったのに気づいていませんでした。  
どれも短くて好きですが、意味が知りたいです。

- `Recody`
  - Recode + Study
- `LIT`
  - learning ? Timer 的な？
- `Otter`
  - 申し訳ないが全く分からなかった。
  - twitter的なのり？

**Comment by ktguy123** [comment]
* Recody
Recode + Study => YES!
* LIT
learning ? Timer 的な？ => "TIL" をひっくり返したもの
* Otter
申し訳ないが全く分からなかった。
twitter的なのり？ => Otterは英語でカワウソ。生き物だとアイコンの作成がしやすいと思って。

**Comment by suntorybikkle** [comment]
なるほど、良いですね。
カワウソは一度調べたけどなぜに？
どれかを採用してdevelopを更新させていただきます。

**Comment by suntorybikkle** [comment]
暫定ですが、変更したので閉じます。
