### ISSUE TITLE
科目テーブル取得のリクエストjsonの修正相談

### ISSUE THREAD

**Issue by ktguy123** [suntorybikkle/test#21]
現在、科目テーブル取得のjsonは以下の通りの実装予定となっている。  
```js
 {
 	"subjects":[
 		{
 		"subId": 0,　　　"_comment":重複なし, デフォルトは0
     		"name": "国語",　"_comment":重複なし, デフォルトは空文字, Userによる空文字での登録はできない
     		"display": true,
     		"color": 　　　　"_comment":重複あり（サーバ側で決定する）
     			{
     				r:123
         			g:123
         			b:123
     			},
     	}
     ]
 }
```

**相談：subjects[].color部の変更をしたいです**  
理由：subjects[].colorが項目が多く不格好。フロント側のパースが手間。10進数だと色相がそろっているかどうか直感的に理解できない。  
      
提案1:CSSの形で定義 (文字列渡し)  
```js
"backgroundColor":"#fcc"
```
パースせずそのまま使用できる。すっきりする。(Vueで処理しやすい)
  
提案2:16進数＋配列
```js
"color":[f, c, c]
```
すっきりする。

**Comment by suntorybikkle** [comment]
### 見解

実装としては、旧来のもの含めどの提案でも問題ありません。  
個人的に提案１が文字列渡してるだけで簡単に思えるため、希望します。

### 疑問

- 色の種類は多くないけど、#の後に３桁で表現するタイプにするのでしょうか？
  - `#ffcccc`→`#fcc` この記法は表現できる色パターンが少ないよね？
- 提案１の要素名が変わっているのは意図したことでしょうか？
  - `color`→`backgroundColor` jsonもこの名前？

**Comment by ktguy123** [comment]
色の種類は多くないけど、#の後に３桁で表現するタイプにするのでしょうか？
#ffcccc→#fcc この記法は表現できる色パターンが少ないよね？
  
→ 16^3色あるので十分かと思った。どちらでもよいです。
<hr>
提案１の要素名が変わっているのは意図したことでしょうか？
color→backgroundColor jsonもこの名前？  
  
  
→ `backgroundColor:"#fcc"`にするとresponseのJsonをそのまま反映させることができるからいいかなと思った。
  
でもバリデーションしないで使うのはいけない気がするので、`color:"#ffcccc"`でいいです。
  
もしくは`rgb:"#ffcccc"`とか？（rgb指定なんだなってぱっと見わかりやすいかも？）

**Comment by suntorybikkle** [comment]
把握いたしました。  

- `rgb:"#ffcccc"`
- `color:"#ffcccc"`
- `rgb:"#fcc"`
- `color:"#fcc"`

のいずれかでお願いします。

**Comment by ktguy123** [comment]
`rgb:"#ffcccc"`でいきます
